export { default as Register } from "./register/Register";
export { default as DetailInfo } from "./detailInfo/DetailInfo";
export { default as Patient_home_page } from "./Patient_home/Patient_home_page";
export { default as Spinner } from "./spinner/Spinner";
export { default as Login } from "./login/Login";
export { default as PatientLogin } from "./login/patient/PatientLogin";
export { default as Patient_register } from "./Patient_home/Regiter Form/Patient_register";
export { default as MainPage } from "./Main_Page/MainPage";
export { default as Services } from "./About_Us/Services";
export { default as Add_doctor } from "./Admin_home/Add_doctor";
export { default as Admin_home_page } from "./Admin_home/Admin_home_page";
export { default as Doctor_page } from "./doctor_module/Doctor_page";
export { default as DoctorServices } from "./doctor_module/DoctorServices";
export { default as Profile } from "./Patient_home/profile/Profile";
export { default as Contact_us } from "./Contact_us/Contact_us";
